#User Configuration

#OE_TERMINAL = "tmux"
IMAGE_INSTALL:append = " cora-pwm cora-dsp gr-cora cora-dashboard cora-ofdm cora-ofdm-demo cora-ofdm-acoustic cora-ofdm-text-demo alsa-utils usbutils"
IMAGE_BOOT_FILES:zynq = "BOOT.BIN boot.scr uImage system.dtb"
